### ISSUE TITLE
Update for the YouTube section

### ISSUE THREAD

**Issue by FarshidNooshi** [aut-datahub/awesome-ai#1]
Hi 
I have some aids to add to this Awesome readme for RL courses and ML-based content.
* [x] [first](https://youtube.com/playlist?list=PLpFYkKZ3fmP7T0datl4ghRebc7nlkmgVI)
* [x] [second](https://youtube.com/playlist?list=PLqYmG7hTraZDM-OYHWgPebj2MfCFzFObQ)

**Comment by AmirMohamadBabaee** [comment]
Thanks, @FarshidNooshi for your issue.
Those are fantastic courses. I'll add them soon.

**Comment by FarshidNooshi** [comment]
Your welcome, mate 👍🏼🤝
